pull sha

diff --git a/.github/workflows/slasher.yml b/.github/workflows/slasher.yml
--- a/.github/workflows/slasher.yml
+++ b/.github/workflows/slasher.yml
@@ -20,12 +20,18 @@ jobs:
           echo "  Event Payload: ${{ toJson(github.event) }}"
           echo "  Repository: ${{ github.repository }}"
           echo "  Pull Request: ${{ github.event.pull_request }}"
-      - name: Get PR branch
+      - name: Get PR merge commit SHA
         env:
           GITHUB_TOKEN: ${{ github.token }}
         run: |
-          PR_BRANCH=$(gh pr view ${{ github.event.issue.number }} --json headRefName --jq .headRefName)
-          [ -n "$PR_BRANCH" ] && echo "PR_BRANCH=$PR_BRANCH" >> $GITHUB_ENV || (echo "Failed to identify PR branch" && exit 1)
+          PR_MERGE_SHA=$(gh pr view ${{ github.event.issue.number }} --json potentialMergeCommit --jq .potentialMergeCommit.oid)
+          [ -n "$PR_MERGE_SHA" ] && echo "PR_MERGE_SHA=$PR_MERGE_SHA" >> $GITHUB_ENV || (echo "Failed to identify PR merge commit SHA" && exit 1)
+#      - name: Get PR branch
+#        env:
+#          GITHUB_TOKEN: ${{ github.token }}
+#        run: |
+#          PR_BRANCH=$(gh pr view ${{ github.event.issue.number }} --json headRefName --jq .headRefName)
+#          [ -n "$PR_BRANCH" ] && echo "PR_BRANCH=$PR_BRANCH" >> $GITHUB_ENV || (echo "Failed to identify PR branch" && exit 1)
       - name: Slash command dispatch
         uses: peter-evans/slash-command-dispatch@v4
         with:
@@ -34,9 +40,8 @@ jobs:
           event-type-suffix: -deploy
           commands: |
             e2e           
-            mgmt-cluster 
           dispatch-type: workflow
           static-args: |
             comment-id=${{ github.event.comment.id }}
             pr-number=${{ github.event.issue.number }}
-            ref=${{ env.PR_BRANCH }}
+            ref=${{ env.PR_MERGE_SHA }}
